import { Language } from ".";

const languages: Language[] = [
	{
		locale: "ach-UG",
		name: "Acholi",
		nativeName: "Lwo",
		direction: "ltr",
		country: "Uganda",
		countryCode: "ug",
		emoji: "🇺🇬",
		hex: "#D90000",
		rgb: [217, 0, 0],
		color: 14221312
	},
	{
		locale: "aa-ER",
		name: "Afar",
		nativeName: "Qafaraf",
		direction: "ltr",
		country: "Eritrea",
		countryCode: "er",
		emoji: "🇪🇷",
		hex: "#3C8BDC",
		rgb: [60, 139, 220],
		color: 3967964
	},
	{
		locale: "af-ZA",
		name: "Afrikaans",
		nativeName: "Afrikaans",
		direction: "ltr",
		country: "South Africa",
		countryCode: "za",
		emoji: "🇿🇦",
		hex: "#FFB81C",
		rgb: [255, 182, 18],
		color: 16758290
	},
	{
		locale: "ak-GH",
		name: "Akan",
		nativeName: "Ákán",
		direction: "ltr",
		country: "Ghana",
		countryCode: "gh",
		emoji: "🇬🇭",
		hex: "#CF0921",
		rgb: [207, 9, 33],
		color: 13568289
	},
	{
		locale: "tw-TW",
		name: "Akan, Twi",
		nativeName: "Ákán, Twi",
		direction: "ltr",
		country: "Ghana",
		countryCode: "gh",
		emoji: "🇬🇭",
		hex: "#CF0921",
		rgb: [207, 9, 33],
		color: 13568289
	},
	{
		locale: "sq-AL",
		name: "Albanian",
		nativeName: "Shqip",
		direction: "ltr",
		country: "Albania",
		countryCode: "al",
		emoji: "🇦🇱",
		hex: "#FF0000",
		rgb: [255, 0, 0],
		color: 16711680
	},
	{
		locale: "am-ET",
		name: "Amharic",
		nativeName: "አማርኛ",
		direction: "ltr",
		country: "Ethiopia",
		countryCode: "et",
		emoji: "🇪🇹",
		hex: "#078930",
		rgb: [7, 137, 48],
		color: 493872
	},
	{
		locale: "ar",
		name: "Arabic",
		nativeName: "العربية",
		direction: "rtl",
		country: "Jordan",
		countryCode: "jo",
		emoji: "🇯🇴",
		hex: "#007A3D",
		rgb: [0, 122, 61],
		color: 31293
	},
	{
		locale: "ar-BH",
		name: "Arabic, Bahrain",
		nativeName: "العربية، البحرين",
		direction: "rtl",
		country: "Bahrain",
		countryCode: "bh",
		emoji: "🇧🇭",
		hex: "#F21731",
		rgb: [242, 23, 49],
		color: 15865649
	},
	{
		locale: "ar-EG",
		name: "Arabic, Egypt",
		nativeName: "العربية، مصر",
		direction: "rtl",
		country: "Egypt",
		countryCode: "eg",
		emoji: "🇪🇬",
		hex: "#CE1126",
		rgb: [206, 17, 38],
		color: 13504806
	},
	{
		locale: "ar-SA",
		name: "Arabic, Saudi Arabia",
		nativeName: "العربية، السعودية",
		direction: "rtl",
		country: "Saudi Arabia",
		countryCode: "sa",
		emoji: "🇸🇦",
		hex: "#006C35",
		rgb: [0, 108, 53],
		color: 27701
	},
	{
		locale: "ar-YE",
		name: "Arabic, Yemen",
		nativeName: "العربية، اليمن",
		direction: "rtl",
		country: "Yemen",
		countryCode: "ye",
		emoji: "🇾🇪",
		hex: "#CE1126",
		rgb: [206, 17, 38],
		color: 13504806
	},
	{
		locale: "an-ES",
		name: "Aragonese",
		nativeName: "Aragonés",
		direction: "ltr",
		country: "Spain",
		countryCode: "es",
		emoji: "🇪🇸",
		region: "Aragon",
		regionCode: "ar",
		hex: "#FFDA0C",
		rgb: [255, 218, 12],
		color: 16767500
	},
	{
		locale: "hy-AM",
		name: "Armenian",
		nativeName: "հայերեն",
		direction: "ltr",
		country: "Armenia",
		countryCode: "am",
		emoji: "🇦🇲",
		hex: "#D90012",
		rgb: [217, 0, 18],
		color: 14221330
	},
	{
		locale: "frp-IT",
		name: "Arpitan",
		nativeName: "Arpetan",
		direction: "ltr",
		country: "Italy",
		countryCode: "it",
		emoji: "🇮🇹",
		region: "Arpitania",
		regionCode: "frp",
		hex: "#EB1C24",
		rgb: [235, 28, 36],
		color: 15408164
	},
	{
		locale: "as-IN",
		name: "Assamese",
		nativeName: "অসমীয়া",
		direction: "ltr",
		country: "India",
		countryCode: "in",
		emoji: "🇮🇳",
		region: "Assam",
		regionCode: "as",
		hex: "#FF9933",
		rgb: [255, 153, 51],
		color: 16750899
	},
	{
		locale: "ast-ES",
		name: "Asturian",
		nativeName: "Asturianu",
		direction: "ltr",
		country: "Spain",
		countryCode: "es",
		emoji: "🇪🇸",
		region: "Asturias",
		regionCode: "as",
		hex: "#0066FF",
		rgb: [0, 102, 255],
		color: 26367
	},
	{
		locale: "tay-TW",
		name: "Atayal",
		nativeName: "Tayal",
		direction: "ltr",
		country: "Taiwan",
		countryCode: "tw",
		emoji: "🇹🇼",
		hex: "#FE0000",
		rgb: [254, 0, 0],
		color: 16646144
	},
	{
		locale: "av-DA",
		name: "Avaric",
		nativeName: "MагIарул MацI",
		direction: "ltr",
		country: "Russia",
		countryCode: "ru",
		region: "Dagestan",
		regionCode: "da",
		hex: "#0039A6",
		rgb: [0, 57, 166],
		color: 14758
	},
	{
		locale: "ae-IR",
		name: "Avestan",
		nativeName: "𐬎𐬞𐬀𐬯𐬙𐬀𐬎𐬎𐬀𐬐𐬀𐬉𐬥𐬀",
		direction: "ltr",
		country: "Iran",
		countryCode: "ir",
		region: "Avesta",
		regionCode: "ae",
		hex: "#da0000",
		rgb: [218, 0, 0],
		color: 14286848
	},
	{
		locale: "ay-BO",
		name: "Aymara",
		nativeName: "Aymar aru",
		direction: "ltr",
		country: "Bolivia",
		countryCode: "bo",
		emoji: "🇧🇴",
		region: "Andes Mountains",
		regionCode: "ay",
		hex: "#FFFFFF",
		rgb: [255, 255, 255],
		color: 16777215
	},
	{
		locale: "az-AZ",
		name: "Azerbaijani",
		nativeName: "Azərbaycan",
		direction: "ltr",
		country: "Azerbaijan",
		countryCode: "az",
		emoji: "🇦🇿",
		hex: "#0092BC",
		rgb: [0, 146, 188],
		color: 37564
	},
	{
		locale: "ban-ID",
		name: "Balinese",
		nativeName: "ᬪᬵᬱᬩᬮᬶ",
		direction: "ltr",
		country: "Indonesia",
		countryCode: "id",
		emoji: "🇮🇩",
		region: "Bali",
		regionCode: "ban",
		hex: "#FF0000",
		rgb: [255, 0, 0],
		color: 16711680
	},
	{
		locale: "bal-BA",
		name: "Balochi",
		nativeName: "Balòci",
		direction: "ltr",
		country: "Pakistan",
		countryCode: "pk",
		emoji: "🇵🇰",
		region: "Balochistan",
		regionCode: "ba",
		hex: "#004226",
		rgb: [0, 66, 38],
		color: 16934
	},
	{
		locale: "bm-ML",
		name: "Bambara",
		nativeName: "Bamanankan",
		direction: "ltr",
		country: "Mali",
		countryCode: "ml",
		emoji: "🇲🇱",
		region: "Bamana",
		regionCode: "bm",
		hex: "#FCD116",
		rgb: [20, 181, 58],
		color: 1357114
	},
	{
		locale: "ba-RU",
		name: "Bashkir",
		nativeName: "Башҡортса",
		direction: "ltr",
		country: "Russia",
		countryCode: "ru",
		region: "Bashkortostan",
		regionCode: "ba",
		hex: "#0070FF",
		rgb: [0, 112, 255],
		color: 28927
	},
	{
		locale: "eu-ES",
		name: "Basque",
		nativeName: "Euskara",
		direction: "ltr",
		country: "Spain",
		countryCode: "es",
		emoji: "🇪🇸",
		region: "Basque Country",
		regionCode: "pv",
		hex: "#009B48",
		rgb: [0, 155, 72],
		color: 39752
	},
	{
		locale: "be-BY",
		name: "Belarusian",
		nativeName: "беларуская",
		direction: "ltr",
		country: "Belarus",
		countryCode: "by",
		emoji: "🇧🇾",
		hex: "#CF101A",
		rgb: [207, 16, 26],
		color: 13570074
	},
	{
		locale: "bn-BD",
		name: "Bengali",
		nativeName: "বাংলা",
		direction: "ltr",
		country: "Bangladesh",
		countryCode: "bn",
		emoji: "🇧🇩",
		hex: "#006747",
		rgb: [0, 103, 71],
		color: 26439
	},
	{
		locale: "bn-IN",
		name: "Bengali, India",
		nativeName: "বাংলা, ভারত",
		direction: "ltr",
		country: "India",
		countryCode: "in",
		emoji: "🇮🇳",
		hex: "#FF9933",
		rgb: [255, 153, 51],
		color: 16750899
	},
	{
		locale: "ber-DZ",
		name: "Berber",
		nativeName: "Tamaziɣt",
		direction: "ltr",
		country: "Argelia",
		countryCode: "dk",
		region: "Berber",
		regionCode: "ber",
		hex: "#99CC33",
		rgb: [153, 204, 51],
		color: 10079283
	},
	{
		locale: "bh-IN",
		name: "Bihari",
		nativeName: "Bihari",
		direction: "ltr",
		country: "India",
		countryCode: "in",
		emoji: "🇮🇳",
		region: "Bihar",
		regionCode: "br",
		hex: "#FF9933",
		rgb: [255, 153, 51],
		color: 16750899
	},
	{
		locale: "bfo-BF",
		name: "Birifor",
		nativeName: "Birifor",
		direction: "ltr",
		country: "Burkina Faso",
		countryCode: "bf",
		emoji: "🇧🇫",
		hex: "#009E49",
		rgb: [0, 158, 73],
		color: 40521
	},
	{
		locale: "bi-VU",
		name: "Bislama",
		nativeName: "Bislama",
		direction: "ltr",
		country: "Vanuatu",
		countryCode: "vu",
		emoji: "🇻🇺",
		hex: "#FDCE12",
		rgb: [253, 206, 18],
		color: 16633362
	},
	{
		locale: "bs-BA",
		name: "Bosnian",
		nativeName: "Bosanski",
		direction: "ltr",
		country: "Bosnia and Herzegovina",
		countryCode: "ba",
		emoji: "🇧🇦",
		hex: "#001489",
		rgb: [0, 20, 137],
		color: 5257
	},
	{
		locale: "br-FR",
		name: "Breton",
		nativeName: "Brezhoneg",
		direction: "ltr",
		country: "France",
		countryCode: "fr",
		emoji: "🇫🇷",
		region: "Brittany",
		regionCode: "e",
		hex: "#000000",
		rgb: [0, 0, 0],
		color: 0
	},
	{
		locale: "bg-BG",
		name: "Bulgarian",
		nativeName: "български",
		direction: "ltr",
		country: "Bulgaria",
		countryCode: "bg",
		emoji: "🇧🇬",
		hex: "#009B74",
		rgb: [0, 155, 116],
		color: 39796
	},
	{
		locale: "my-MM",
		name: "Burmese",
		nativeName: "မြန်မာဘာသာ",
		direction: "ltr",
		country: "Myanmar",
		countryCode: "mm",
		emoji: "🇲🇲",
		hex: "#EA2839",
		rgb: [234, 40, 57],
		color: 15345721
	},
	{
		locale: "ca-ES",
		name: "Catalan",
		nativeName: "Català",
		direction: "ltr",
		country: "Spain",
		countryCode: "es",
		emoji: "🇪🇸",
		region: "Catalonia",
		regionCode: "ca",
		hex: "#DA121A",
		rgb: [218, 18, 26],
		color: 14291482
	},
	{
		locale: "ceb-PH",
		name: "Cebuano",
		nativeName: "Sugboanon",
		direction: "ltr",
		country: "Philippines",
		countryCode: "ph",
		emoji: "🇵🇭",
		region: "Central Visayas",
		regionCode: "07",
		hex: "#0038A8",
		rgb: [0, 56, 168],
		color: 14504
	},
	{
		locale: "ch-GU",
		name: "Chamorro",
		nativeName: "Chamoru",
		direction: "ltr",
		country: "Guam",
		countryCode: "gu",
		emoji: "🇬🇺",
		hex: "#00257C",
		rgb: [0, 37, 124],
		color: 9596
	},
	{
		locale: "ce-CE",
		name: "Chechen",
		nativeName: "Нохчийн",
		direction: "ltr",
		country: "Russia",
		countryCode: "es",
		region: "Chechnya",
		regionCode: "ce",
		hex: "#2B7338",
		rgb: [43, 115, 56],
		color: 2847544
	},
	{
		locale: "chr-US",
		name: "Cherokee",
		nativeName: "ᏣᎳᎩ",
		direction: "ltr",
		country: "United States",
		countryCode: "us",
		emoji: "🇺🇸",
		region: "Oklahoma",
		regionCode: "ok",
		hex: "#0A3161",
		rgb: [10, 49, 97],
		color: 668001
	},
	{
		locale: "ny-MW",
		name: "Chewa",
		nativeName: "Chichewa",
		direction: "ltr",
		country: "Malawi",
		countryCode: "mw",
		emoji: "🇲🇼",
		hex: "#CE1126",
		rgb: [206, 17, 38],
		color: 13504806
	},
	{
		locale: "zh-CN",
		name: "Chinese Simplified",
		nativeName: "简体中文",
		direction: "ltr",
		country: "China",
		countryCode: "cn",
		emoji: "🇨🇳",
		hex: "#EE1C25",
		rgb: [238, 28, 37],
		color: 15604773
	},
	{
		locale: "zh-TW",
		name: "Chinese Traditional",
		nativeName: "繁體中文",
		direction: "ltr",
		country: "Taiwan",
		countryCode: "tw",
		emoji: "🇹🇼",
		hex: "#FE0000",
		rgb: [254, 0, 0],
		color: 16646144
	},
	{
		locale: "zh-HK",
		name: "Chinese Traditional, Hong Kong",
		nativeName: "繁體中文,香港",
		direction: "ltr",
		country: "Hong Kong",
		countryCode: "hk",
		emoji: "🇭🇰",
		hex: "#DE2408",
		rgb: [222, 36, 8],
		color: 14558216
	},
	{
		locale: "zh-MO",
		name: "Chinese Traditional, Macau",
		nativeName: "繁體中文,澳門",
		direction: "ltr",
		country: "Macau",
		countryCode: "mo",
		hex: "#00795E",
		rgb: [0, 121, 94],
		color: 31070
	},
	{
		locale: "zh-SG",
		name: "Chinese Traditional, Singapore",
		nativeName: "繁體中文,新加坡",
		direction: "ltr",
		country: "Singapore",
		countryCode: "sg",
		emoji: "🇸🇬",
		hex: "#EF3340",
		rgb: [239, 51, 64],
		color: 15676224
	},
	{
		locale: "cv-CU",
		name: "Chuvash",
		nativeName: "Căvashla",
		direction: "ltr",
		country: "Russia",
		countryCode: "ru",
		region: "Chuvashia",
		regionCode: "cu",
		hex: "#FFDF00",
		rgb: [255, 223, 0],
		color: 16768768
	},
	{
		locale: "kw-GB",
		name: "Cornish",
		nativeName: "Kernowek",
		direction: "ltr",
		country: "United Kingdom",
		countryCode: "gb",
		emoji: "🇬🇧",
		region: "Cornwall",
		regionCode: "con",
		hex: "#000000",
		rgb: [0, 0, 0],
		color: 0
	},
	{
		locale: "co-FR",
		name: "Corsican",
		nativeName: "Corsu",
		direction: "ltr",
		country: "France",
		countryCode: "fr",
		emoji: "🇫🇷",
		region: "Corsica",
		regionCode: "co",
		hex: "#000000",
		rgb: [0, 0, 0],
		color: 0
	},
	{
		locale: "cr-NT",
		name: "Cree",
		nativeName: "ᓀᐦᐃᔭᐍᐏᐣ",
		direction: "ltr",
		country: "Canada",
		countryCode: "ca",
		emoji: "🇨🇦",
		region: "Northwest Territories",
		regionCode: "nt",
		hex: "#2A317D",
		rgb: [42, 49, 125],
		color: 2765181
	},
	{
		locale: "hr-HR",
		name: "Croatian",
		nativeName: "Hrvatski",
		direction: "ltr",
		country: "Croatia",
		countryCode: "hr",
		emoji: "🇭🇷",
		hex: "#C8102E",
		rgb: [200, 16, 46],
		color: 13111342
	},
	{
		locale: "cs-CZ",
		name: "Czech",
		nativeName: "Čeština",
		direction: "ltr",
		country: "Czech Republic",
		countryCode: "cz",
		hex: "#D7141A",
		rgb: [215, 20, 26],
		color: 14095386
	},
	{
		locale: "da-DK",
		name: "Danish",
		nativeName: "Dansk",
		direction: "ltr",
		country: "Denmark",
		countryCode: "dk",
		emoji: "🇩🇰",
		hex: "#C60C30",
		rgb: [198, 12, 48],
		color: 12979248
	},
	{
		locale: "fa-AF",
		name: "Dari",
		nativeName: "دری",
		direction: "rtl",
		country: "Afghanistan",
		countryCode: "af",
		emoji: "🇦🇫",
		hex: "#D32011",
		rgb: [211, 32, 17],
		color: 13836305
	},
	{
		locale: "dv-MV",
		name: "Dhivehi",
		nativeName: "ދިވެހި",
		direction: "rtl",
		country: "Maldives",
		countryCode: "mv",
		emoji: "🇲🇻",
		hex: "#D21034",
		rgb: [210, 16, 52],
		color: 13766708
	},
	{
		locale: "nl-NL",
		name: "Dutch",
		nativeName: "Nederlands",
		direction: "ltr",
		country: "Netherlands",
		countryCode: "nl",
		emoji: "🇳🇱",
		hex: "#FF4F00",
		rgb: [255, 79, 0],
		color: 16731904
	},
	{
		locale: "nl-BE",
		name: "Dutch, Belgium",
		nativeName: "Belgisch-Nederlands",
		direction: "ltr",
		country: "Belgium",
		countryCode: "be",
		emoji: "🇧🇪",
		hex: "#EF3340",
		rgb: [239, 51, 64],
		color: 15676224
	},
	{
		locale: "nl-SR",
		name: "Dutch, Suriname",
		nativeName: "Surinaams-Nederlands",
		direction: "ltr",
		country: "Suriname",
		countryCode: "sr",
		emoji: "🇸🇷",
		hex: "#B40A2D",
		rgb: [180, 10, 45],
		color: 11799085
	},
	{
		locale: "dz-BT",
		name: "Dzongkha",
		nativeName: "རྫོང་ཁ་",
		direction: "ltr",
		country: "Bhutan",
		countryCode: "bt",
		emoji: "🇧🇹",
		hex: "#FF4E12",
		rgb: [255, 78, 18],
		color: 16731666
	},
	{
		locale: "en",
		name: "English",
		nativeName: "English",
		direction: "ltr",
		country: "United Kingdom",
		countryCode: "gb",
		emoji: "🇬🇧",
		hex: "#00247D",
		rgb: [0, 36, 125],
		color: 9341
	},
	{
		locale: "en-UD",
		name: "English (upside down)",
		nativeName: "ɥsıןƃuƎ",
		direction: "ltr",
		country: "United States",
		countryCode: "us",
		emoji: "🇺🇸",
		hex: "#0A3161",
		rgb: [10, 49, 97],
		color: 668001
	},
	{
		locale: "en-AR",
		name: "English, Arabia",
		nativeName: "English, Arabia",
		direction: "ltr",
		country: "United Arab Emirates",
		countryCode: "ae",
		emoji: "🇦🇪",
		hex: "#FF0000",
		rgb: [255, 0, 0],
		color: 16711680
	},
	{
		locale: "en-AU",
		name: "English, Australia",
		nativeName: "English, Australia",
		direction: "ltr",
		country: "Australia",
		countryCode: "au",
		emoji: "🇦🇺",
		hex: "#FFCD00",
		rgb: [255, 205, 0],
		color: 16764160
	},
	{
		locale: "en-BZ",
		name: "English, Belize",
		nativeName: "English, Belize",
		direction: "ltr",
		country: "Belize",
		countryCode: "bz",
		emoji: "🇧🇿",
		hex: "#003F87",
		rgb: [0, 63, 135],
		color: 16263
	},
	{
		locale: "en-CA",
		name: "English, Canada",
		nativeName: "English, Canada",
		direction: "ltr",
		country: "Canada",
		countryCode: "ca",
		emoji: "🇨🇦",
		hex: "#FF0000",
		rgb: [255, 0, 0],
		color: 16711680
	},
	{
		locale: "en-CB",
		name: "English, Caribbean",
		nativeName: "English, Caribbean",
		direction: "ltr",
		country: "United States",
		countryCode: "us",
		emoji: "🇺🇸",
		region: "Caribbean",
		regionCode: "cb",
		hex: "#0A3161",
		rgb: [10, 49, 97],
		color: 668001
	},
	{
		locale: "en-CN",
		name: "English, China",
		nativeName: "English, China",
		direction: "ltr",
		country: "China",
		countryCode: "cn",
		emoji: "🇨🇳",
		hex: "#EE1C25",
		rgb: [238, 28, 37],
		color: 15604773
	},
	{
		locale: "en-DK",
		name: "English, Denmark",
		nativeName: "English, Denmark",
		direction: "ltr",
		country: "Denmark",
		countryCode: "dk",
		emoji: "🇩🇰",
		hex: "#C60C30",
		rgb: [198, 12, 48],
		color: 12979248
	},
	{
		locale: "en-HK",
		name: "English, Hong Kong",
		nativeName: "English, Hong Kong",
		direction: "ltr",
		country: "Hong Kong",
		countryCode: "hk",
		emoji: "🇭🇰",
		hex: "#DE2408",
		rgb: [222, 36, 8],
		color: 14558216
	},
	{
		locale: "en-IN",
		name: "English, India",
		nativeName: "English, India",
		direction: "ltr",
		country: "India",
		countryCode: "in",
		emoji: "🇮🇳",
		hex: "#FF9933",
		rgb: [255, 153, 51],
		color: 16750899
	},
	{
		locale: "en-ID",
		name: "English, Indonesia",
		nativeName: "English, Indonesia",
		direction: "ltr",
		country: "Indonesia",
		countryCode: "id",
		emoji: "🇮🇩",
		hex: "#EF3340",
		rgb: [239, 51, 64],
		color: 15676224
	},
	{
		locale: "en-IE",
		name: "English, Ireland",
		nativeName: "English, Ireland",
		direction: "ltr",
		country: "Ireland",
		countryCode: "ie",
		emoji: "🇮🇪",
		hex: "#169B62",
		rgb: [22, 155, 98],
		color: 1481570
	},
	{
		locale: "en-JM",
		name: "English, Jamaica",
		nativeName: "English, Jamaica",
		direction: "ltr",
		country: "Jamaica",
		countryCode: "jm",
		emoji: "🇯🇲",
		hex: "#009B3A",
		rgb: [0, 155, 58],
		color: 39738
	},
	{
		locale: "en-JA",
		name: "English, Japan",
		nativeName: "English, Japan",
		direction: "ltr",
		country: "Japan",
		countryCode: "ja",
		emoji: "🇯🇵",
		hex: "#BC002D",
		rgb: [188, 0, 45],
		color: 12320813
	},
	{
		locale: "en-MY",
		name: "English, Malaysia",
		nativeName: "English, Malaysia",
		direction: "ltr",
		country: "Malaysia",
		countryCode: "my",
		emoji: "🇲🇾",
		hex: "#FFCC00",
		rgb: [255, 204, 0],
		color: 16763904
	},
	{
		locale: "en-NZ",
		name: "English, New Zealand",
		nativeName: "English, New Zealand",
		direction: "ltr",
		country: "New Zealand",
		countryCode: "nz",
		emoji: "🇳🇿",
		hex: "#000000",
		rgb: [0, 0, 0],
		color: 0
	},
	{
		locale: "en-NO",
		name: "English, Norway",
		nativeName: "English, Norway",
		direction: "ltr",
		country: "Norway",
		countryCode: "no",
		emoji: "🇳🇴",
		hex: "#BA0C2F",
		rgb: [186, 12, 47],
		color: 12192815
	},
	{
		locale: "en-PH",
		name: "English, Philippines",
		nativeName: "English, Philippines",
		direction: "ltr",
		country: "Philippines",
		countryCode: "ph",
		emoji: "🇵🇭",
		hex: "#0038A8",
		rgb: [0, 56, 168],
		color: 14504
	},
	{
		locale: "en-PR",
		name: "English, Puerto Rico",
		nativeName: "English, Puerto Rico",
		direction: "ltr",
		country: "Puerto Rico",
		countryCode: "pr",
		emoji: "🇵🇷",
		hex: "#E92228",
		rgb: [233, 34, 40],
		color: 15278632
	},
	{
		locale: "en-SG",
		name: "English, Singapore",
		nativeName: "English, Singapore",
		direction: "ltr",
		country: "Singapore",
		countryCode: "sg",
		emoji: "🇸🇬",
		hex: "#EF3340",
		rgb: [239, 51, 64],
		color: 15676224
	},
	{
		locale: "en-ZA",
		name: "English, South Africa",
		nativeName: "English, South Africa",
		direction: "ltr",
		country: "South Africa",
		countryCode: "za",
		emoji: "🇿🇦",
		hex: "#FFB81C",
		rgb: [255, 182, 18],
		color: 16758290
	},
	{
		locale: "en-SE",
		name: "English, Sweden",
		nativeName: "English, Sweden",
		direction: "ltr",
		country: "Sweden",
		countryCode: "se",
		emoji: "🇸🇪",
		hex: "#FECC02",
		rgb: [254, 204, 2],
		color: 16698370
	},
	{
		locale: "en-GB",
		name: "English, United Kingdom",
		nativeName: "English, United Kingdom",
		direction: "ltr",
		country: "United Kingdom",
		countryCode: "gb",
		emoji: "🇬🇧",
		hex: "#00247D",
		rgb: [0, 36, 125],
		color: 9341
	},
	{
		locale: "en-US",
		name: "English, United States",
		nativeName: "English, United States",
		direction: "ltr",
		country: "United States",
		countryCode: "us",
		emoji: "🇺🇸",
		hex: "#0A3161",
		rgb: [10, 49, 97],
		color: 668001
	},
	{
		locale: "en-ZW",
		name: "English, Zimbabwe",
		nativeName: "English, Zimbabwe",
		direction: "ltr",
		country: "Zimbabwe",
		countryCode: "zw",
		emoji: "🇿🇼",
		hex: "#FFD200",
		rgb: [255, 210, 0],
		color: 16765440
	},
	{
		locale: "eo-UY",
		name: "Esperanto",
		nativeName: "Esperanto",
		direction: "ltr",
		country: "International",
		countryCode: "uy",
		hex: "#009900",
		rgb: [0, 153, 0],
		color: 39168
	},
	{
		locale: "et-EE",
		name: "Estonian",
		nativeName: "Eesti keel",
		direction: "ltr",
		country: "Estonia",
		countryCode: "ee",
		emoji: "🇪🇪",
		hex: "#0072CE",
		rgb: [0, 114, 206],
		color: 29390
	},
	{
		locale: "ee-GH",
		name: "Ewe",
		nativeName: "Eʋegbe",
		direction: "ltr",
		country: "Ghana",
		countryCode: "gh",
		emoji: "🇬🇭",
		hex: "#CF0921",
		rgb: [207, 9, 33],
		color: 13568289
	},
	{
		locale: "fo-FO",
		name: "Faroese",
		nativeName: "Føroyskt",
		direction: "ltr",
		country: "Faroe Islands",
		countryCode: "fo",
		emoji: "🇫🇴",
		hex: "#0165BF",
		rgb: [1, 101, 191],
		color: 91583
	},
	{
		locale: "fj-FJ",
		name: "Fijian",
		nativeName: "Vakaviti",
		direction: "ltr",
		country: "Fiji Islands",
		countryCode: "fj",
		hex: "#68bfe5",
		rgb: [104, 191, 229],
		color: 6864869
	},
	{
		locale: "fil-PH",
		name: "Filipino",
		nativeName: "Wikang Filipino",
		direction: "ltr",
		country: "Philippines",
		countryCode: "ph",
		emoji: "🇵🇭",
		hex: "#0038A8",
		rgb: [0, 56, 168],
		color: 14504
	},
	{
		locale: "fi-FI",
		name: "Finnish",
		nativeName: "Suomi",
		direction: "ltr",
		country: "Finland",
		countryCode: "fi",
		emoji: "🇫🇮",
		hex: "#002F6C",
		rgb: [0, 47, 108],
		color: 12140
	},
	{
		locale: "vls-BE",
		name: "Flemish",
		nativeName: "Vlaams",
		direction: "ltr",
		country: "Belgium",
		countryCode: "be",
		emoji: "🇧🇪",
		region: "Flanders",
		regionCode: "vlg",
		hex: "#FEEA28",
		rgb: [254, 234, 40],
		color: 16706088
	},
	{
		locale: "fra-DE",
		name: "Franconian",
		nativeName: "Franken",
		direction: "ltr",
		country: "Germany",
		countryCode: "de",
		emoji: "🇩🇪",
		region: "Franconia",
		regionCode: "fra",
		hex: "#CE1126",
		rgb: [206, 17, 38],
		color: 13504806
	},
	{
		locale: "fr-FR",
		name: "French",
		nativeName: "Français",
		direction: "ltr",
		country: "French",
		countryCode: "fr",
		hex: "#318CE7",
		rgb: [49, 140, 231],
		color: 3247335
	},
	{
		locale: "fr-BE",
		name: "French, Belgium",
		nativeName: "Français, Belgique",
		direction: "ltr",
		country: "Belgium",
		countryCode: "be",
		emoji: "🇧🇪",
		hex: "#EF3340",
		rgb: [239, 51, 64],
		color: 15676224
	},
	{
		locale: "fr-CA",
		name: "French, Canada",
		nativeName: "Français, Canada",
		direction: "ltr",
		country: "Canada",
		countryCode: "ca",
		emoji: "🇨🇦",
		hex: "#FF0000",
		rgb: [255, 0, 0],
		color: 16711680
	},
	{
		locale: "fr-LU",
		name: "French, Luxembourg",
		nativeName: "Français, Luxembourgeois",
		direction: "ltr",
		country: "Luxembourg",
		countryCode: "lu",
		emoji: "🇱🇺",
		hex: "#EF3340",
		rgb: [239, 51, 64],
		color: 15676224
	},
	{
		locale: "fr-QC",
		name: "French, Quebec",
		nativeName: "Français, Québec",
		direction: "ltr",
		country: "Canada",
		countryCode: "ca",
		emoji: "🇨🇦",
		region: "Quebec",
		regionCode: "qc",
		hex: "#003DA5",
		rgb: [0, 61, 165],
		color: 15781
	},
	{
		locale: "fr-CH",
		name: "French, Switzerland",
		nativeName: "Français, Suisse",
		direction: "ltr",
		country: "Switzerland",
		countryCode: "ch",
		emoji: "🇨🇭",
		hex: "#DA291C",
		rgb: [218, 41, 28],
		color: 14297372
	},
	{
		locale: "fy-NL",
		name: "Frisian",
		country: "Netherlands",
		nativeName: "Frysk",
		direction: "ltr",
		countryCode: "nl",
		emoji: "🇳🇱",
		region: "Friesland",
		regionCode: "fr",
		hex: "#0155A5",
		rgb: [1, 85, 165],
		color: 87461
	},
	{
		locale: "fur-IT",
		name: "Friulian",
		nativeName: "Furlan",
		direction: "ltr",
		country: "Italy",
		countryCode: "it",
		emoji: "🇮🇹",
		region: "Friuli",
		regionCode: "fur",
		hex: "#196DB6",
		rgb: [25, 109, 182],
		color: 1666486
	},
	{
		locale: "ff-ZA",
		name: "Fula",
		nativeName: "Fulfulde",
		direction: "ltr",
		country: "South Africa",
		countryCode: "za",
		emoji: "🇿🇦",
		hex: "#FFB81C",
		rgb: [255, 182, 18],
		color: 16758290
	},
	{
		locale: "gaa-GH",
		name: "Ga",
		nativeName: "Gã",
		direction: "ltr",
		country: "Ghana",
		countryCode: "gh",
		emoji: "🇬🇭",
		hex: "#CF0921",
		rgb: [207, 9, 33],
		color: 13568289
	},
	{
		locale: "gl-ES",
		name: "Galician",
		nativeName: "Galego",
		direction: "ltr",
		country: "Spain",
		countryCode: "es",
		emoji: "🇪🇸",
		region: "Galiza",
		regionCode: "ga",
		hex: "#0099CC",
		rgb: [0, 153, 204],
		color: 39372
	},
	{
		locale: "ka-GE",
		name: "Georgian",
		nativeName: "ქართული",
		direction: "ltr",
		country: "Georgia",
		countryCode: "ge",
		emoji: "🇬🇪",
		hex: "#FF0000",
		rgb: [255, 0, 0],
		color: 16711680
	},
	{
		locale: "de-DE",
		name: "German",
		nativeName: "Deutsch",
		direction: "ltr",
		country: "Germany",
		countryCode: "de",
		emoji: "🇩🇪",
		hex: "#DD0000",
		rgb: [221, 0, 0],
		color: 14483456
	},
	{
		locale: "de-AT",
		name: "German, Austria",
		nativeName: "Deutsch, Österreich",
		direction: "ltr",
		country: "Austria",
		countryCode: "at",
		emoji: "🇦🇹",
		hex: "#ED2939",
		rgb: [237, 41, 57],
		color: 15542585
	},
	{
		locale: "de-BE",
		name: "German, Belgium",
		nativeName: "Deutsch, Belgien",
		direction: "ltr",
		country: "Belgium",
		countryCode: "be",
		emoji: "🇧🇪",
		hex: "#EF3340",
		rgb: [239, 51, 64],
		color: 15676224
	},
	{
		locale: "de-LI",
		name: "German, Liechtenstein",
		nativeName: "Deutsch, Liechtenstein",
		direction: "ltr",
		country: "Liechtenstein",
		countryCode: "li",
		emoji: "🇱🇮",
		hex: "#002780",
		rgb: [0, 39, 128],
		color: 10112
	},
	{
		locale: "de-LU",
		name: "German, Luxembourg",
		nativeName: "Deutsch, Luxemburg",
		direction: "ltr",
		country: "Luxembourg",
		countryCode: "lu",
		emoji: "🇱🇺",
		hex: "#EF3340",
		rgb: [239, 51, 64],
		color: 15676224
	},
	{
		locale: "de-CH",
		name: "German, Switzerland",
		nativeName: "Deutsch, Schweiz",
		direction: "ltr",
		country: "Switzerland",
		countryCode: "ch",
		emoji: "🇨🇭",
		hex: "#DA291C",
		rgb: [218, 41, 28],
		color: 14297372
	},
	{
		locale: "got-DE",
		name: "Gothic",
		nativeName: "𐌲𐌿𐍄𐍂𐌰𐌶𐌳𐌰",
		direction: "ltr",
		country: "Germany",
		countryCode: "de",
		emoji: "🇩🇪",
		hex: "#800080",
		rgb: [128, 0, 128],
		color: 8388736
	},
	{
		locale: "el-GR",
		name: "Greek",
		nativeName: "Ελληνικά",
		direction: "ltr",
		country: "Greece",
		countryCode: "gr",
		emoji: "🇬🇷",
		hex: "#0D5EAF",
		rgb: [13, 94, 175],
		color: 876207
	},
	{
		locale: "el-CY",
		name: "Greek, Cyprus",
		nativeName: "Ελληνικά, Κύπρος",
		direction: "ltr",
		country: "Cyprus",
		countryCode: "cy",
		emoji: "🇨🇾",
		hex: "#D57800",
		rgb: [213, 120, 0],
		color: 13989888
	},
	{
		locale: "kl-GL",
		name: "Greenlandic",
		nativeName: "Kalaallisut",
		direction: "ltr",
		country: "Denmark",
		countryCode: "dk",
		emoji: "🇩🇰",
		region: "Greenland",
		regionCode: "gl",
		hex: "#C60C30",
		rgb: [198, 12, 48],
		color: 12979248
	},
	{
		locale: "gn-PY",
		name: "Guarani",
		nativeName: "Avañeʼẽ",
		direction: "ltr",
		country: "Paraguay",
		countryCode: "py",
		emoji: "🇵🇾",
		hex: "#D52B1E",
		rgb: [213, 43, 30],
		color: 13970206
	},
	{
		locale: "gu-IN",
		name: "Gujarati",
		nativeName: "ગુજરાતી",
		direction: "ltr",
		country: "India",
		countryCode: "in",
		emoji: "🇮🇳",
		hex: "#FF9933",
		rgb: [255, 153, 51],
		color: 16750899
	},
	{
		locale: "ht-HT",
		name: "Haitian Creole",
		nativeName: "Kreyòl ayisyen",
		direction: "ltr",
		country: "Haiti",
		countryCode: "ht",
		emoji: "🇭🇹",
		hex: "#00209F",
		rgb: [0, 32, 159],
		color: 8351
	},
	{
		locale: "ha-HG",
		name: "Hausa",
		nativeName: "Hausa",
		direction: "ltr",
		country: "Nigeria",
		countryCode: "ng",
		emoji: "🇳🇬",
		hex: "#008753",
		rgb: [0, 135, 83],
		color: 34643
	},
	{
		locale: "haw-US",
		name: "Hawaiian",
		nativeName: "Ōlelo Hawaiʻi",
		direction: "ltr",
		country: "United States",
		countryCode: "us",
		emoji: "🇺🇸",
		region: "Hawaii",
		regionCode: "hi",
		hex: "#00247D",
		rgb: [0, 36, 125],
		color: 9341
	},
	{
		locale: "he-IL",
		name: "Hebrew",
		nativeName: "עִברִית",
		direction: "rtl",
		country: "Israel",
		countryCode: "il",
		emoji: "🇮🇱",
		hex: "#0038b8",
		rgb: [0, 56, 184],
		color: 14520
	},
	{
		locale: "hz-NA",
		name: "Herero",
		nativeName: "Otjiherero",
		direction: "ltr",
		country: "Namibia",
		countryCode: "na",
		emoji: "🇳🇦",
		hex: "#D21034",
		rgb: [210, 16, 52],
		color: 13766708
	},
	{
		locale: "hil-PH",
		name: "Hiligaynon",
		nativeName: "Ilonggo",
		direction: "ltr",
		country: "Philippines",
		countryCode: "ph",
		emoji: "🇵🇭",
		region: "Western Visayas",
		regionCode: "06",
		hex: "#0038A8",
		rgb: [0, 56, 168],
		color: 14504
	},
	{
		locale: "hi-IN",
		name: "Hindi",
		nativeName: "हिंदी",
		direction: "ltr",
		country: "India",
		countryCode: "in",
		emoji: "🇮🇳",
		hex: "#FF9933",
		rgb: [255, 153, 51],
		color: 16750899
	},
	{
		locale: "ho-PG",
		name: "Hiri Motu",
		nativeName: "Hiri Motu",
		direction: "ltr",
		country: "Papua New Guinea",
		countryCode: "pg",
		emoji: "🇵🇬",
		hex: "#CE1126",
		rgb: [206, 17, 38],
		color: 13504806
	},
	{
		locale: "hmn-CN",
		name: "Hmong",
		nativeName: "Hmoob",
		direction: "ltr",
		country: "China",
		countryCode: "cn",
		emoji: "🇨🇳",
		hex: "#EE1C25",
		rgb: [238, 28, 37],
		color: 15604773
	},
	{
		locale: "hu-HU",
		name: "Hungarian",
		nativeName: "Magyar",
		direction: "ltr",
		country: "Hungary",
		countryCode: "hu",
		emoji: "🇭🇺",
		hex: "#CE2939",
		rgb: [206, 41, 57],
		color: 13510969
	},
	{
		locale: "is-IS",
		name: "Icelandic",
		nativeName: "Íslenska",
		direction: "ltr",
		country: "Iceland",
		countryCode: "is",
		emoji: "🇮🇸",
		hex: "#02529C",
		rgb: [2, 82, 156],
		color: 152220
	},
	{
		locale: "io-EN",
		name: "Ido",
		nativeName: "Ido",
		direction: "ltr",
		country: "International",
		countryCode: "en",
		hex: "#127ec9",
		rgb: [18, 126, 201],
		color: 1212105
	},
	{
		locale: "ig-NG",
		name: "Igbo",
		nativeName: "Igbo",
		direction: "ltr",
		country: "Nigeria",
		countryCode: "ng",
		emoji: "🇳🇬",
		hex: "#008753",
		rgb: [0, 135, 83],
		color: 34643
	},
	{
		locale: "ilo-PH",
		name: "Ilokano",
		nativeName: "Ilokano",
		direction: "ltr",
		country: "Philippines",
		countryCode: "ph",
		emoji: "🇵🇭",
		hex: "#0038A8",
		rgb: [0, 56, 168],
		color: 14504
	},
	{
		locale: "id-ID",
		name: "Indonesian",
		nativeName: "Bahasa Indonesia",
		direction: "ltr",
		country: "Indonesia",
		countryCode: "id",
		emoji: "🇮🇩",
		hex: "#EF3340",
		rgb: [239, 51, 64],
		color: 15676224
	},
	{
		locale: "iu-NU",
		name: "Inuktitut",
		nativeName: "ᐃᓄᒃᑎᑐᑦ",
		direction: "ltr",
		country: "Canada",
		countryCode: "ca",
		emoji: "🇨🇦",
		region: "Nunavut",
		regionCode: "nu",
		hex: "#D51516",
		rgb: [213, 21, 22],
		color: 13964566
	},
	{
		locale: "ga-IE",
		name: "Irish",
		nativeName: "Gaeilge",
		direction: "ltr",
		country: "Ireland",
		countryCode: "ie",
		emoji: "🇮🇪",
		hex: "#169B62",
		rgb: [22, 155, 98],
		color: 1481570
	},
	{
		locale: "it-IT",
		name: "Italian",
		nativeName: "Italiano",
		direction: "ltr",
		country: "Italy",
		countryCode: "it",
		emoji: "🇮🇹",
		hex: "#008C45",
		rgb: [0, 140, 69],
		color: 35909
	},
	{
		locale: "it-CH",
		name: "Italian, Switzerland",
		nativeName: "Italiano, Svizzera",
		direction: "ltr",
		country: "Switzerland",
		countryCode: "ch",
		emoji: "🇨🇭",
		hex: "#DA291C",
		rgb: [218, 41, 28],
		color: 14297372
	},
	{
		locale: "ja-JP",
		name: "Japanese",
		nativeName: "日本語",
		direction: "ltr",
		country: "Japan",
		countryCode: "ja",
		emoji: "🇯🇵",
		hex: "#BC002D",
		rgb: [188, 0, 45],
		color: 12320813
	},
	{
		locale: "jv-ID",
		name: "Javanese",
		nativeName: "Basa Jawa",
		direction: "ltr",
		country: "Indonesia",
		countryCode: "id",
		emoji: "🇮🇩",
		hex: "#EF3340",
		rgb: [239, 51, 64],
		color: 15676224
	},
	{
		locale: "quc-GT",
		name: "K'iche'",
		nativeName: "Quiché",
		direction: "ltr",
		country: "Guatemala",
		countryCode: "gt",
		emoji: "🇬🇹",
		hex: "#4997D0",
		rgb: [73, 151, 208],
		color: 4822992
	},
	{
		locale: "kab-KAB",
		name: "Kabyle",
		nativeName: "Taqbaylit",
		direction: "ltr",
		country: "Algeria",
		countryCode: "dz",
		emoji: "🇩🇿",
		region: "Kabylia",
		regionCode: "kab",
		hex: "#CD263E",
		rgb: [205, 38, 62],
		color: 13444670
	},
	{
		locale: "kn-IN",
		name: "Kannada",
		nativeName: "ಕನ್ನಡ",
		direction: "ltr",
		country: "India",
		countryCode: "in",
		emoji: "🇮🇳",
		hex: "#FF9933",
		rgb: [255, 153, 51],
		color: 16750899
	},
	{
		locale: "pam-PH",
		name: "Kapampangan",
		nativeName: "Kapampangan",
		direction: "ltr",
		country: "Philippines",
		countryCode: "ph",
		emoji: "🇵🇭",
		hex: "#81007F",
		rgb: [129, 0, 127],
		color: 8454271
	},
	{
		locale: "ks-IN",
		name: "Kashmiri",
		nativeName: "कॉशुर",
		direction: "ltr",
		country: "India",
		countryCode: "in",
		emoji: "🇮🇳",
		hex: "#FF9933",
		rgb: [255, 153, 51],
		color: 16750899
	},
	{
		locale: "ks-PK",
		name: "Kashmiri, Pakistan",
		nativeName: "कॉशुर, पाकिस्तान",
		direction: "ltr",
		country: "Pakistan",
		countryCode: "pk",
		emoji: "🇵🇰",
		hex: "#00401A",
		rgb: [0, 64, 26],
		color: 16410
	},
	{
		locale: "csb-PL",
		name: "Kashubian",
		nativeName: "Kaszëbsczi",
		direction: "ltr",
		country: "Poland",
		countryCode: "pl",
		emoji: "🇵🇱",
		hex: "#FFFF00",
		rgb: [255, 255, 0],
		color: 16776960
	},
	{
		locale: "kk-KZ",
		name: "Kazakh",
		nativeName: "Қазақша",
		direction: "ltr",
		country: "Kazakhstan",
		countryCode: "kz",
		emoji: "🇰🇿",
		hex: "#00AFCA",
		rgb: [0, 175, 202],
		color: 45002
	},
	{
		locale: "km-KH",
		name: "Khmer",
		nativeName: "ភាសាខ្មែរ",
		direction: "ltr",
		country: "Cambodia",
		countryCode: "kh",
		emoji: "🇰🇭",
		hex: "#032EA1",
		rgb: [3, 46, 161],
		color: 208545
	},
	{
		locale: "rw-RW",
		name: "Kinyarwanda",
		nativeName: "Ikinyarwanda",
		direction: "ltr",
		country: "Rwanda",
		countryCode: "rw",
		emoji: "🇷🇼",
		hex: "#E5BE01",
		rgb: [229, 190, 1],
		color: 15056385
	},
	{
		locale: "tlh-AA",
		name: "Klingon",
		nativeName: "TlhIngan Hol",
		direction: "ltr",
		country: "United States",
		countryCode: "us",
		emoji: "🇺🇸",
		hex: "#008852",
		rgb: [0, 136, 82],
		color: 34898
	},
	{
		locale: "kv-KO",
		name: "Komi",
		nativeName: "Коми кыв",
		direction: "ltr",
		country: "Russia",
		countryCode: "ru",
		region: "Komi",
		regionCode: "ko",
		hex: "#009B3A",
		rgb: [0, 155, 58],
		color: 39738
	},
	{
		locale: "kg-CG",
		name: "Kongo",
		nativeName: "Kikongo",
		direction: "ltr",
		country: "Congo",
		countryCode: "cd",
		emoji: "🇨🇬",
		hex: "#009543",
		rgb: [0, 149, 67],
		color: 38211
	},
	{
		locale: "kok-IN",
		name: "Konkani",
		nativeName: "कोंकणी",
		direction: "ltr",
		country: "India",
		countryCode: "in",
		emoji: "🇮🇳",
		hex: "#FF9933",
		rgb: [255, 153, 51],
		color: 16750899
	},
	{
		locale: "ko-KR",
		name: "Korean",
		nativeName: "한국어",
		direction: "ltr",
		country: "South Korea",
		countryCode: "kr",
		hex: "#CD2E3A",
		rgb: [205, 46, 58],
		color: 13446714
	},
	{
		locale: "ku-TR",
		name: "Kurdish",
		nativeName: "Kurdî",
		direction: "ltr",
		country: "Iran",
		countryCode: "ir",
		region: "Kurdistan",
		regionCode: "ku",
		hex: "#278E43",
		rgb: [39, 138, 65],
		color: 2591297
	},
	{
		locale: "kmr-TR",
		name: "Kurmanji (Kurdish)",
		nativeName: "Kurmancî",
		direction: "ltr",
		country: "Iran",
		countryCode: "ir",
		region: "Kurdistan",
		regionCode: "ku",
		hex: "#278E43",
		rgb: [39, 138, 65],
		color: 2591297
	},
	{
		locale: "kj-AO",
		name: "Kwanyama",
		nativeName: "Oshikwanyama",
		direction: "ltr",
		country: "Angola",
		countryCode: "ao",
		emoji: "🇦🇴",
		hex: "#C8102E",
		rgb: [204, 9, 47],
		color: 13371695
	},
	{
		locale: "ky-KG",
		name: "Kyrgyz",
		nativeName: "Кыргызча",
		direction: "ltr",
		country: "Kyrgyzstan",
		countryCode: "kg",
		emoji: "🇰🇬",
		hex: "#FF0000",
		rgb: [255, 0, 0],
		color: 16711680
	},
	{
		locale: "lo-LA",
		name: "Lao",
		nativeName: "ລາວ",
		direction: "ltr",
		country: "Laos",
		countryCode: "la",
		hex: "#CE1126",
		rgb: [206, 17, 38],
		color: 13504806
	},
	{
		locale: "la-LA",
		name: "Latin",
		nativeName: "Latina",
		direction: "ltr",
		country: "Vatican City",
		countryCode: "va",
		hex: "#FFE000",
		rgb: [255, 224, 0],
		color: 16769024
	},
	{
		locale: "lv-LV",
		name: "Latvian",
		nativeName: "Latviešu",
		direction: "ltr",
		country: "Latvia",
		countryCode: "lv",
		emoji: "🇱🇻",
		hex: "#A4343A",
		rgb: [164, 52, 58],
		color: 10761274
	},
	{
		locale: "lij-IT",
		name: "Ligurian",
		nativeName: "Ligure",
		direction: "ltr",
		country: "Italy",
		countryCode: "it",
		emoji: "🇮🇹",
		region: "Liguria",
		regionCode: "lij",
		hex: "#009C31",
		rgb: [0, 156, 49],
		color: 39985
	},
	{
		locale: "li-LI",
		name: "Limburgish",
		nativeName: "Limburgs",
		direction: "ltr",
		country: "Netherlands",
		countryCode: "nl",
		emoji: "🇳🇱",
		region: "Limburg",
		regionCode: "li",
		hex: "#2D558E",
		rgb: [45, 85, 142],
		color: 2971022
	},
	{
		locale: "ln-CD",
		name: "Lingala",
		nativeName: "Lingála",
		direction: "ltr",
		country: "Congo",
		countryCode: "cd",
		emoji: "🇨🇬",
		hex: "#0085CA",
		rgb: [0, 133, 202],
		color: 34250
	},
	{
		locale: "lt-LT",
		name: "Lithuanian",
		nativeName: "Lietuvių",
		direction: "ltr",
		country: "Lithuania",
		countryCode: "lt",
		emoji: "🇱🇹",
		hex: "#FDB913",
		rgb: [253, 185, 19],
		color: 16627987
	},
	{
		locale: "jbo-EN",
		name: "Lojban",
		nativeName: "La .lojban.",
		direction: "ltr",
		country: "United States",
		countryCode: "us",
		emoji: "🇺🇸",
		hex: "#000063",
		rgb: [0, 0, 99],
		color: 99
	},
	{
		locale: "lol-US",
		name: "LOLCAT",
		nativeName: "LOLCAT",
		direction: "ltr",
		country: "United States",
		countryCode: "us",
		emoji: "🇺🇸",
		hex: "#B8D251",
		rgb: [184, 210, 81],
		color: 12112465
	},
	{
		locale: "nds-DE",
		name: "Low German",
		nativeName: "Plattdüütsch",
		direction: "ltr",
		country: "Germany",
		countryCode: "de",
		emoji: "🇩🇪",
		hex: "#DD0000",
		rgb: [221, 0, 0],
		color: 14483456
	},
	{
		locale: "dsb-DE",
		name: "Lower Sorbian",
		nativeName: "Dolnoserbski",
		direction: "ltr",
		country: "Germany",
		countryCode: "de",
		emoji: "🇩🇪",
		hex: "#0C4076",
		rgb: [12, 64, 118],
		color: 802934
	},
	{
		locale: "lg-UG",
		name: "Luganda",
		nativeName: "Oluganda",
		direction: "ltr",
		country: "Uganda",
		countryCode: "ug",
		emoji: "🇺🇬",
		hex: "#D90000",
		rgb: [217, 0, 0],
		color: 14221312
	},
	{
		locale: "luy-KE",
		name: "Luhya",
		nativeName: "Oluluhya",
		direction: "ltr",
		country: "Kenya",
		countryCode: "ke",
		emoji: "🇰🇪",
		hex: "#BB0000",
		rgb: [187, 0, 0],
		color: 12255232
	},
	{
		locale: "lb-LU",
		name: "Luxembourgish",
		nativeName: "Lëtzebuergesch",
		direction: "ltr",
		country: "Luxembourg",
		countryCode: "lu",
		emoji: "🇱🇺",
		hex: "#EF3340",
		rgb: [239, 51, 64],
		color: 15676224
	},
	{
		locale: "mk-MK",
		name: "Macedonian",
		nativeName: "Македонски",
		direction: "ltr",
		country: "North Macedonia",
		countryCode: "mk",
		hex: "#CE2028",
		rgb: [206, 32, 40],
		color: 13508648
	},
	{
		locale: "mai-IN",
		name: "Maithili",
		nativeName: "मैथिली",
		direction: "ltr",
		country: "India",
		countryCode: "in",
		emoji: "🇮🇳",
		hex: "#FF9933",
		rgb: [255, 153, 51],
		color: 16750899
	},
	{
		locale: "mg-MG",
		name: "Malagasy",
		nativeName: "Malagasy",
		direction: "ltr",
		country: "Madagascar",
		countryCode: "mg",
		emoji: "🇲🇬",
		hex: "#00843D",
		rgb: [0, 132, 61],
		color: 33853
	},
	{
		locale: "ms-MY",
		name: "Malay",
		nativeName: "Bahasa Melayu",
		direction: "ltr",
		country: "Malaysia",
		countryCode: "my",
		emoji: "🇲🇾",
		hex: "#FFCC00",
		rgb: [255, 204, 0],
		color: 16763904
	},
	{
		locale: "ms-BN",
		name: "Malay, Brunei",
		nativeName: "Bahasa Melayu Brunei",
		direction: "ltr",
		country: "Brunei",
		countryCode: "bn",
		emoji: "🇧🇳",
		hex: "#FCE300",
		rgb: [252, 227, 0],
		color: 16573184
	},
	{
		locale: "ml-IN",
		name: "Malayalam",
		nativeName: "മലയാളം",
		direction: "ltr",
		country: "India",
		countryCode: "in",
		emoji: "🇮🇳",
		hex: "#FF9933",
		rgb: [255, 153, 51],
		color: 16750899
	},
	{
		locale: "mt-MT",
		name: "Maltese",
		nativeName: "Malti",
		direction: "ltr",
		country: "Malta",
		countryCode: "mt",
		emoji: "🇲🇹",
		hex: "#C01B22",
		rgb: [192, 27, 34],
		color: 12589858
	},
	{
		locale: "gv-IM",
		name: "Manx",
		nativeName: "Gaelg",
		direction: "ltr",
		country: "United Kingdom",
		countryCode: "gb",
		emoji: "🇬🇧",
		region: "Isle of Man",
		regionCode: "im",
		hex: "#CF142B",
		rgb: [207, 20, 43],
		color: 13571115
	},
	{
		locale: "mi-NZ",
		name: "Maori",
		nativeName: "Māori",
		direction: "ltr",
		country: "New Zealand",
		countryCode: "nz",
		emoji: "🇳🇿",
		hex: "#000000",
		rgb: [0, 0, 0],
		color: 0
	},
	{
		locale: "arn-CL",
		name: "Mapudungun",
		nativeName: "Mapudungun",
		direction: "ltr",
		country: "Chile",
		countryCode: "cl",
		emoji: "🇨🇱",
		hex: "#EF3340",
		rgb: [239, 51, 64],
		color: 15676224
	},
	{
		locale: "mr-IN",
		name: "Marathi",
		nativeName: "मराठी",
		direction: "ltr",
		country: "India",
		countryCode: "in",
		emoji: "🇮🇳",
		hex: "#FF9933",
		rgb: [255, 153, 51],
		color: 16750899
	},
	{
		locale: "mh-MH",
		name: "Marshallese",
		nativeName: "Kajin M̧ajeļ",
		direction: "ltr",
		country: "Marshall Islands",
		countryCode: "mh",
		emoji: "🇲🇭",
		hex: "#003087",
		rgb: [0, 48, 135],
		color: 12423
	},
	{
		locale: "moh-CA",
		name: "Mohawk",
		nativeName: "Kanienʼkéha",
		direction: "ltr",
		country: "Canada",
		countryCode: "ca",
		emoji: "🇨🇦",
		hex: "#D0021B",
		rgb: [208, 2, 27],
		color: 13632027
	},
	{
		locale: "mn-MN",
		name: "Mongolian",
		nativeName: "Монгол",
		direction: "ltr",
		country: "Mongolia",
		countryCode: "mn",
		emoji: "🇲🇳",
		hex: "#DA2032",
		rgb: [218, 32, 50],
		color: 14295090
	},
	{
		locale: "sr-Cyrl-ME",
		name: "Montenegrin (Cyrillic)",
		nativeName: "Црногорски",
		direction: "ltr",
		country: "Montenegro",
		countryCode: "me",
		emoji: "🇲🇪",
		hex: "#C40308",
		rgb: [196, 3, 8],
		color: 12845832
	},
	{
		locale: "me-ME",
		name: "Montenegrin (Latin)",
		nativeName: "Crnogorski",
		direction: "ltr",
		country: "Montenegro",
		countryCode: "me",
		emoji: "🇲🇪",
		hex: "#C40308",
		rgb: [196, 3, 8],
		color: 12845832
	},
	{
		locale: "mos-MOS",
		name: "Mossi",
		nativeName: "Mooré",
		direction: "ltr",
		country: "Burkina Faso",
		countryCode: "bf",
		emoji: "🇧🇫",
		hex: "#009E49",
		rgb: [0, 158, 73],
		color: 40521
	},
	{
		locale: "na-NR",
		name: "Nauru",
		nativeName: "Dorerin Naoero",
		direction: "ltr",
		country: "Nauru",
		countryCode: "nr",
		emoji: "🇳🇷",
		hex: "#012169",
		rgb: [1, 33, 105],
		color: 74089
	},
	{
		locale: "ng-NA",
		name: "Ndonga",
		nativeName: "Ndonga",
		direction: "ltr",
		country: "Namibia",
		countryCode: "na",
		emoji: "🇳🇦",
		hex: "#C8102E",
		rgb: [200, 16, 46],
		color: 13111342
	},
	{
		locale: "ne-NP",
		name: "Nepali",
		nativeName: "नेपाली",
		direction: "ltr",
		country: "Nepal",
		countryCode: "np",
		emoji: "🇳🇵",
		hex: "#DC143C",
		rgb: [220, 20, 60],
		color: 14423100
	},
	{
		locale: "ne-IN",
		name: "Nepali, India",
		nativeName: "नेपाली, भारत",
		direction: "ltr",
		country: "India",
		countryCode: "in",
		emoji: "🇮🇳",
		hex: "#FF9933",
		rgb: [255, 153, 51],
		color: 16750899
	},
	{
		locale: "pcm-NG",
		name: "Nigerian Pidgin",
		nativeName: "Naija",
		direction: "ltr",
		country: "Nigeria",
		countryCode: "ng",
		emoji: "🇳🇬",
		hex: "#008753",
		rgb: [0, 135, 83],
		color: 34643
	},
	{
		locale: "se-NO",
		name: "Northern Sami",
		nativeName: "Davvisámegiella",
		direction: "ltr",
		country: "Norway",
		countryCode: "no",
		emoji: "🇳🇴",
		hex: "#144997",
		rgb: [20, 73, 151],
		color: 1329559
	},
	{
		locale: "ns-ZA",
		name: "Northern Sotho",
		nativeName: "Sesotho sa Leboa",
		direction: "ltr",
		country: "South Africa",
		countryCode: "za",
		emoji: "🇿🇦",
		hex: "#FFB81C",
		rgb: [255, 182, 18],
		color: 16758290
	},
	{
		locale: "no-NO",
		name: "Norwegian",
		nativeName: "Norsk",
		direction: "ltr",
		country: "Norway",
		countryCode: "no",
		emoji: "🇳🇴",
		hex: "#BA0C2F",
		rgb: [186, 12, 47],
		color: 12192815
	},
	{
		locale: "nb-NO",
		name: "Norwegian Bokmal",
		nativeName: "Norsk Bokmål",
		direction: "ltr",
		country: "Norway",
		countryCode: "no",
		emoji: "🇳🇴",
		hex: "#BA0C2F",
		rgb: [186, 12, 47],
		color: 12192815
	},
	{
		locale: "nn-NO",
		name: "Norwegian Nynorsk",
		nativeName: "Norsk Nynorsk",
		direction: "ltr",
		country: "Norway",
		countryCode: "no",
		emoji: "🇳🇴",
		hex: "#BA0C2F",
		rgb: [186, 12, 47],
		color: 12192815
	},
	{
		locale: "oc-FR",
		name: "Occitan",
		nativeName: "Occitan",
		direction: "ltr",
		country: "France",
		countryCode: "fr",
		emoji: "🇫🇷",
		region: "Occitanie",
		regionCode: "oc",
		hex: "#C40026",
		rgb: [196, 0, 38],
		color: 12845094
	},
	{
		locale: "or-IN",
		name: "Odia",
		nativeName: "ଓଡ଼ିଆ",
		direction: "ltr",
		country: "India",
		countryCode: "in",
		emoji: "🇮🇳",
		hex: "#FF9933",
		rgb: [255, 153, 51],
		color: 16750899
	},
	{
		locale: "oj-CA",
		name: "Ojibwe",
		nativeName: "ᐊᓂᐦᔑᓈᐯᒧᐎᓐ",
		direction: "ltr",
		country: "Canada",
		countryCode: "ca",
		emoji: "🇨🇦",
		region: "Ojibwewaki",
		regionCode: "oj",
		hex: "#000000",
		rgb: [0, 0, 0],
		color: 0
	},
	{
		locale: "om-ET",
		name: "Oromo",
		nativeName: "Oromoo",
		direction: "ltr",
		country: "Ethiopia",
		countryCode: "et",
		emoji: "🇪🇹",
		hex: "#009A44",
		rgb: [0, 154, 68],
		color: 39492
	},
	{
		locale: "os-SE",
		name: "Ossetian",
		nativeName: "Ирон ӕвзаг",
		direction: "ltr",
		country: "Russia",
		countryCode: "ru",
		region: "North Ossetia–Alania",
		regionCode: "os",
		hex: "#EF4135",
		rgb: [250, 60, 50],
		color: 16399410
	},
	{
		locale: "pi-IN",
		name: "Pali",
		nativeName: "पालि",
		direction: "ltr",
		country: "India",
		countryCode: "in",
		emoji: "🇮🇳",
		hex: "#FF9933",
		rgb: [255, 153, 51],
		color: 16750899
	},
	{
		locale: "pap-PAP",
		name: "Papiamento",
		nativeName: "Papiamentu",
		direction: "ltr",
		country: "Aruba",
		countryCode: "aw",
		emoji: "🇦🇼",
		hex: "#FBE122",
		rgb: [251, 225, 34],
		color: 16507170
	},
	{
		locale: "ps-AF",
		name: "Pashto",
		nativeName: "پښتو",
		direction: "rtl",
		country: "Afghanistan",
		countryCode: "af",
		emoji: "🇦🇫",
		hex: "#D32011",
		rgb: [211, 32, 17],
		color: 13836305
	},
	{
		locale: "fa-IR",
		name: "Persian",
		nativeName: "فارسی",
		direction: "rtl",
		country: "Iran",
		countryCode: "ir",
		hex: "#DA0000",
		rgb: [218, 0, 0],
		color: 14286848
	},
	{
		locale: "en-PT",
		name: "Pirate English",
		nativeName: "Pirate English",
		direction: "ltr",
		country: "United Kingdom",
		countryCode: "gb",
		emoji: "🇬🇧",
		hex: "#000000",
		rgb: [0, 0, 0],
		color: 0
	},
	{
		locale: "pl-PL",
		name: "Polish",
		nativeName: "Polski",
		direction: "ltr",
		country: "Poland",
		countryCode: "pl",
		emoji: "🇵🇱",
		hex: "#D22730",
		rgb: [210, 39, 48],
		color: 13772592
	},
	{
		locale: "pt-PT",
		name: "Portuguese",
		nativeName: "Português",
		direction: "ltr",
		country: "Portugal",
		countryCode: "pt",
		emoji: "🇵🇹",
		hex: "#FF0000",
		rgb: [255, 0, 0],
		color: 16711680
	},
	{
		locale: "pt-BR",
		name: "Portuguese, Brazilian",
		nativeName: "Português do Brasil",
		direction: "ltr",
		country: "Brazil",
		countryCode: "br",
		emoji: "🇧🇷",
		hex: "#009C3B",
		rgb: [0, 156, 59],
		color: 39995
	},
	{
		locale: "pa-IN",
		name: "Punjabi",
		nativeName: "ਪੰਜਾਬੀ",
		direction: "ltr",
		country: "India",
		countryCode: "in",
		emoji: "🇮🇳",
		hex: "#FF9933",
		rgb: [255, 153, 51],
		color: 16750899
	},
	{
		locale: "pa-PK",
		name: "Punjabi, Pakistan",
		nativeName: "پن٘جابی",
		direction: "ltr",
		country: "Pakistan",
		countryCode: "pk",
		emoji: "🇵🇰",
		hex: "#00401A",
		rgb: [0, 64, 26],
		color: 16410
	},
	{
		locale: "qu-PE",
		name: "Quechua",
		nativeName: "Kechua",
		direction: "ltr",
		country: "Peru",
		countryCode: "pe",
		emoji: "🇵🇪",
		hex: "#D91023",
		rgb: [217, 16, 35],
		color: 14225443
	},
	{
		locale: "qya-AA",
		name: "Quenya",
		nativeName: "Quenya",
		direction: "ltr",
		country: "Middle-earth",
		countryCode: "aa",
		hex: "#008852",
		rgb: [0, 136, 82],
		color: 34898
	},
	{
		locale: "ro-RO",
		name: "Romanian",
		nativeName: "Limba română",
		direction: "ltr",
		country: "Romania",
		countryCode: "ro",
		emoji: "🇷🇴",
		hex: "#FCD116",
		rgb: [252, 209, 22],
		color: 16568598
	},
	{
		locale: "rm-CH",
		name: "Romansh",
		nativeName: "Rumantsch",
		direction: "ltr",
		country: "Switzerland",
		countryCode: "ch",
		emoji: "🇨🇭",
		hex: "#DA291C",
		rgb: [218, 41, 28],
		color: 14297372
	},
	{
		locale: "rn-BI",
		name: "Rundi",
		nativeName: "ÍkiRǔndi",
		direction: "ltr",
		country: "Republic of Burundi",
		countryCode: "bi",
		hex: "#18B637",
		rgb: [24, 182, 55],
		color: 1619511
	},
	{
		locale: "ru-RU",
		name: "Russian",
		nativeName: "Русский",
		direction: "ltr",
		country: "Russia",
		countryCode: "ru",
		hex: "#DB0D20",
		rgb: [219, 13, 32],
		color: 14355744
	},
	{
		locale: "ru-BY",
		name: "Russian, Belarus",
		nativeName: "Русский, Беларусь",
		direction: "ltr",
		country: "Belarus",
		countryCode: "by",
		emoji: "🇧🇾",
		hex: "#CF101A",
		rgb: [207, 16, 26],
		color: 13570074
	},
	{
		locale: "ru-MD",
		name: "Russian, Moldova",
		nativeName: "Русский, Молдова",
		direction: "ltr",
		country: "Moldova",
		countryCode: "md",
		hex: "#0046AE",
		rgb: [0, 70, 174],
		color: 18094
	},
	{
		locale: "ru-UA",
		name: "Russian, Ukraine",
		nativeName: "Русский, Украина",
		direction: "ltr",
		country: "Ukraine",
		countryCode: "ua",
		emoji: "🇺🇦",
		hex: "#FFD700",
		rgb: [255, 215, 0],
		color: 16766720
	},
	{
		locale: "ry-UA",
		name: "Rusyn",
		nativeName: "Русины",
		direction: "ltr",
		country: "Ukraine",
		countryCode: "ua",
		emoji: "🇺🇦",
		hex: "#FFD700",
		rgb: [255, 215, 0],
		color: 16766720
	},
	{
		locale: "sah-SAH",
		name: "Sakha",
		nativeName: "Саха тыла",
		direction: "ltr",
		country: "Russia",
		countryCode: "ru",
		region: "Republic of Sakha (Yakutia)",
		regionCode: "sah",
		hex: "#1199FF",
		rgb: [17, 153, 255],
		color: 1153535
	},
	{
		locale: "sg-CF",
		name: "Sango",
		nativeName: "Yângâ tî Sängö",
		direction: "ltr",
		country: "Central African Republic",
		countryCode: "cf",
		emoji: "🇨🇫",
		hex: "#003082",
		rgb: [0, 48, 130],
		color: 12418
	},
	{
		locale: "sa-IN",
		name: "Sanskrit",
		nativeName: "संस्कृतम्",
		direction: "ltr",
		country: "India",
		countryCode: "in",
		emoji: "🇮🇳",
		hex: "#FF9933",
		rgb: [255, 153, 51],
		color: 16750899
	},
	{
		locale: "sat-IN",
		name: "Santali",
		nativeName: "संथाली",
		direction: "ltr",
		country: "India",
		countryCode: "in",
		emoji: "🇮🇳",
		hex: "#FF9933",
		rgb: [255, 153, 51],
		color: 16750899
	},
	{
		locale: "sc-IT",
		name: "Sardinian",
		nativeName: "Limba Sarda",
		direction: "ltr",
		country: "Italy",
		countryCode: "it",
		emoji: "🇮🇹",
		region: "Sardinia",
		regionCode: "sc",
		hex: "#D81921",
		rgb: [216, 25, 33],
		color: 14162209
	},
	{
		locale: "sco-GB",
		name: "Scots",
		nativeName: "Scoats leid",
		direction: "ltr",
		country: "United Kingdom",
		countryCode: "gb",
		emoji: "🇬🇧",
		region: "Scotland",
		regionCode: "sct",
		hex: "#005EB8",
		rgb: [0, 94, 184],
		color: 24248
	},
	{
		locale: "gd-GB",
		name: "Scottish Gaelic",
		nativeName: "Gàidhlig",
		direction: "ltr",
		country: "United Kingdom",
		countryCode: "gb",
		emoji: "🇬🇧",
		region: "Scotland",
		regionCode: "sct",
		hex: "#005EB8",
		rgb: [0, 94, 184],
		color: 24248
	},
	{
		locale: "sr-SP",
		name: "Serbian (Cyrillic)",
		nativeName: "Српска ћирилица",
		direction: "ltr",
		country: "Serbia",
		countryCode: "rs",
		emoji: "🇷🇸",
		hex: "#C6363C",
		rgb: [198, 54, 60],
		color: 12990012
	},
	{
		locale: "sr-CS",
		name: "Serbian (Latin)",
		nativeName: "Latinski Srpski",
		direction: "ltr",
		country: "Serbia",
		countryCode: "rs",
		emoji: "🇷🇸",
		hex: "#C6363C",
		rgb: [198, 54, 60],
		color: 12990012
	},
	{
		locale: "sh-HR",
		name: "Serbo-Croatian",
		nativeName: "Srpskohrvatski",
		direction: "ltr",
		country: "Croatia",
		countryCode: "hr",
		emoji: "🇭🇷",
		hex: "#C8102E",
		rgb: [200, 16, 46],
		color: 13111342
	},
	{
		locale: "crs-SC",
		name: "Seychellois Creole",
		nativeName: "Kreol",
		direction: "ltr",
		country: "Seychelles",
		countryCode: "sc",
		emoji: "🇸🇨",
		hex: "#D72323",
		rgb: [215, 35, 35],
		color: 14099235
	},
	{
		locale: "sn-ZW",
		name: "Shona",
		nativeName: "ChiShona",
		direction: "ltr",
		country: "Zimbabwe",
		countryCode: "zw",
		emoji: "🇿🇼",
		hex: "#FCE300",
		rgb: [252, 227, 0],
		color: 16573184
	},
	{
		locale: "ii-CN",
		name: "Sichuan Yi",
		nativeName: "ꆈꌠꉙ",
		direction: "ltr",
		country: "China",
		countryCode: "cn",
		emoji: "🇨🇳",
		hex: "#EE1C25",
		rgb: [238, 28, 37],
		color: 15604773
	},
	{
		locale: "sd-PK",
		name: "Sindhi",
		nativeName: "سنڌي",
		direction: "rtl",
		country: "Pakistan",
		countryCode: "pk",
		emoji: "🇵🇰",
		hex: "#00401A",
		rgb: [0, 64, 26],
		color: 16410
	},
	{
		locale: "si-LK",
		name: "Sinhala",
		nativeName: "සිංහල",
		direction: "ltr",
		country: "Sri Lanka",
		countryCode: "lk",
		emoji: "🇱🇰",
		hex: "#FFBF24",
		rgb: [255, 191, 36],
		color: 16760612
	},
	{
		locale: "sk-SK",
		name: "Slovak",
		nativeName: "Slovenčina",
		direction: "ltr",
		country: "Slovakia",
		countryCode: "sk",
		emoji: "🇸🇰",
		hex: "#EE1620",
		rgb: [238, 22, 32],
		color: 15603232
	},
	{
		locale: "sl-SI",
		name: "Slovenian",
		nativeName: "Slovenščina",
		direction: "ltr",
		country: "Slovenia",
		countryCode: "si",
		emoji: "🇸🇮",
		hex: "#005CE6",
		rgb: [0, 92, 230],
		color: 23782
	},
	{
		locale: "so-SO",
		name: "Somali",
		nativeName: "Af Soomaali",
		direction: "ltr",
		country: "Somalia",
		countryCode: "so",
		emoji: "🇸🇴",
		hex: "#4189DD",
		rgb: [65, 137, 221],
		color: 4295133
	},
	{
		locale: "son-ZA",
		name: "Songhay",
		nativeName: "Songhai",
		direction: "ltr",
		country: "South Africa",
		countryCode: "za",
		emoji: "🇿🇦",
		hex: "#FFB81C",
		rgb: [255, 182, 18],
		color: 16758290
	},
	{
		locale: "ckb-IR",
		name: "Sorani (Kurdish)",
		nativeName: "سۆرانی",
		direction: "rtl",
		country: "Iran",
		countryCode: "ir",
		region: "Kurdistan",
		regionCode: "ku",
		hex: "#278E43",
		rgb: [39, 138, 65],
		color: 2591297
	},
	{
		locale: "nr-ZA",
		name: "Southern Ndebele",
		nativeName: "Transvaal Ndebele",
		direction: "ltr",
		country: "South Africa",
		countryCode: "za",
		emoji: "🇿🇦",
		hex: "#FFB81C",
		rgb: [255, 182, 18],
		color: 16758290
	},
	{
		locale: "sma-NO",
		name: "Southern Sami",
		nativeName: "Åarjelsaemien gïele",
		direction: "ltr",
		country: "Norway",
		countryCode: "no",
		emoji: "🇳🇴",
		hex: "#BA0C2F",
		rgb: [186, 12, 47],
		color: 12192815
	},
	{
		locale: "st-ZA",
		name: "Southern Sotho",
		nativeName: "SeSotho",
		direction: "ltr",
		country: "South Africa",
		countryCode: "za",
		emoji: "🇿🇦",
		hex: "#FFB81C",
		rgb: [255, 182, 18],
		color: 16758290
	},
	{
		locale: "es-ES",
		name: "Spanish",
		nativeName: "Español",
		direction: "ltr",
		country: "Spain",
		countryCode: "es",
		emoji: "🇪🇸",
		hex: "#AA151B",
		rgb: [170, 21, 27],
		color: 11146523
	},
	{
		locale: "es-EM",
		name: "Spanish (Modern)",
		nativeName: "Español (Moderno)",
		direction: "ltr",
		country: "Spain",
		countryCode: "es",
		emoji: "🇪🇸",
		hex: "#AA151B",
		rgb: [170, 21, 27],
		color: 11146523
	},
	{
		locale: "es-AR",
		name: "Spanish, Argentina",
		nativeName: "Español argentino",
		direction: "ltr",
		country: "Argentina",
		countryCode: "ar",
		emoji: "🇦🇷",
		hex: "#6CACE4",
		rgb: [108, 172, 228],
		color: 7122148
	},
	{
		locale: "es-BO",
		name: "Spanish, Bolivia",
		nativeName: "Español boliviano",
		direction: "ltr",
		country: "Bolivia",
		countryCode: "bo",
		emoji: "🇧🇴",
		hex: "#007A33",
		rgb: [0, 122, 51],
		color: 31283
	},
	{
		locale: "es-CL",
		name: "Spanish, Chile",
		nativeName: "Español chileno",
		direction: "ltr",
		country: "Chile",
		countryCode: "cl",
		emoji: "🇨🇱",
		hex: "#EF3340",
		rgb: [239, 51, 64],
		color: 15676224
	},
	{
		locale: "es-CO",
		name: "Spanish, Colombia",
		nativeName: "Español colombiano",
		direction: "ltr",
		country: "Colombia",
		countryCode: "co",
		emoji: "🇨🇴",
		hex: "#FCD116",
		rgb: [252, 209, 22],
		color: 16568598
	},
	{
		locale: "es-CR",
		name: "Spanish, Costa Rica",
		nativeName: "Español costarricense",
		direction: "ltr",
		country: "Costa Rica",
		countryCode: "cr",
		emoji: "🇨🇷",
		hex: "#CE1126",
		rgb: [206, 17, 38],
		color: 13504806
	},
	{
		locale: "es-DO",
		name: "Spanish, Dominican Republic",
		nativeName: "Español dominicano",
		direction: "ltr",
		country: "Dominican Republic",
		countryCode: "do",
		emoji: "🇩🇴",
		hex: "#002D62",
		rgb: [0, 45, 98],
		color: 11618
	},
	{
		locale: "es-EC",
		name: "Spanish, Ecuador",
		nativeName: "Español ecuatoriano",
		direction: "ltr",
		country: "Ecuador",
		countryCode: "ec",
		emoji: "🇪🇨",
		hex: "#FFD100",
		rgb: [255, 209, 0],
		color: 16765184
	},
	{
		locale: "es-SV",
		name: "Spanish, El Salvador",
		nativeName: "Español salvadoreño",
		direction: "ltr",
		country: "El Salvador",
		countryCode: "sv",
		emoji: "🇸🇻",
		hex: "#0047AB",
		rgb: [0, 71, 171],
		color: 18347
	},
	{
		locale: "es-GT",
		name: "Spanish, Guatemala",
		nativeName: "Español guatemalteco",
		direction: "ltr",
		country: "Guatemala",
		countryCode: "gt",
		emoji: "🇬🇹",
		hex: "#4997D0",
		rgb: [73, 151, 208],
		color: 4822992
	},
	{
		locale: "es-HN",
		name: "Spanish, Honduras",
		nativeName: "Español hondureño",
		direction: "ltr",
		country: "Honduras",
		countryCode: "hn",
		emoji: "🇭🇳",
		hex: "#0072CE",
		rgb: [0, 114, 206],
		color: 29390
	},
	{
		locale: "es-419",
		name: "Spanish, Latin America",
		nativeName: "Español latinoamericano",
		direction: "ltr",
		country: "Spain",
		countryCode: "es",
		emoji: "🇪🇸",
		hex: "#AA151B",
		rgb: [170, 21, 27],
		color: 11146523
	},
	{
		locale: "es-MX",
		name: "Spanish, Mexico",
		nativeName: "Español mexicano",
		direction: "ltr",
		country: "Mexico",
		countryCode: "mx",
		emoji: "🇲🇽",
		hex: "#006847",
		rgb: [0, 104, 71],
		color: 26695
	},
	{
		locale: "es-NI",
		name: "Spanish, Nicaragua",
		nativeName: "Español nicaragüense",
		direction: "ltr",
		country: "Nicaragua",
		countryCode: "ni",
		emoji: "🇳🇮",
		hex: "#0067C6",
		rgb: [0, 103, 198],
		color: 26566
	},
	{
		locale: "es-PA",
		name: "Spanish, Panama",
		nativeName: "Español panameño",
		direction: "ltr",
		country: "Panama",
		countryCode: "pa",
		emoji: "🇵🇦",
		hex: "#DA121A",
		rgb: [218, 18, 26],
		color: 14291482
	},
	{
		locale: "es-PY",
		name: "Spanish, Paraguay",
		nativeName: "Español paraguayo",
		direction: "ltr",
		country: "Paraguay",
		countryCode: "py",
		emoji: "🇵🇾",
		hex: "#D52B1E",
		rgb: [213, 43, 30],
		color: 13970206
	},
	{
		locale: "es-PE",
		name: "Spanish, Peru",
		nativeName: "Español peruano",
		direction: "ltr",
		country: "Peru",
		countryCode: "pe",
		emoji: "🇵🇪",
		hex: "#D91023",
		rgb: [217, 16, 35],
		color: 14225443
	},
	{
		locale: "es-PR",
		name: "Spanish, Puerto Rico",
		nativeName: "Español puertorriqueño",
		direction: "ltr",
		country: "Puerto Rico",
		countryCode: "pr",
		emoji: "🇵🇷",
		hex: "#E92228",
		rgb: [233, 34, 40],
		color: 15278632
	},
	{
		locale: "es-US",
		name: "Spanish, United States",
		nativeName: "Español estadounidense",
		direction: "ltr",
		country: "United States",
		countryCode: "us",
		emoji: "🇺🇸",
		hex: "#0A3161",
		rgb: [10, 49, 97],
		color: 668001
	},
	{
		locale: "es-UY",
		name: "Spanish, Uruguay",
		nativeName: "Español uruguayo",
		direction: "ltr",
		country: "Uruguay",
		countryCode: "uy",
		emoji: "🇺🇾",
		hex: "#0038A8",
		rgb: [0, 56, 168],
		color: 14504
	},
	{
		locale: "es-VE",
		name: "Spanish, Venezuela",
		nativeName: "Español venezolano",
		direction: "ltr",
		country: "Venezuela",
		countryCode: "ve",
		emoji: "🇻🇪",
		hex: "#EF3340",
		rgb: [239, 51, 64],
		color: 15676224
	},
	{
		locale: "su-ID",
		name: "Sundanese",
		nativeName: "Basa Sunda",
		direction: "ltr",
		country: "Indonesia",
		countryCode: "id",
		emoji: "🇮🇩",
		hex: "#EF3340",
		rgb: [239, 51, 64],
		color: 15676224
	},
	{
		locale: "sw",
		name: "Swahili",
		nativeName: "Kiswahili",
		direction: "ltr",
		country: "Kenya",
		countryCode: "ke",
		emoji: "🇰🇪",
		hex: "#BB0000",
		rgb: [187, 0, 0],
		color: 12255232
	},
	{
		locale: "sw-KE",
		name: "Swahili, Kenya",
		nativeName: "Kiswahili, Kenya",
		direction: "ltr",
		country: "Kenya",
		countryCode: "ke",
		emoji: "🇰🇪",
		hex: "#BB0000",
		rgb: [187, 0, 0],
		color: 12255232
	},
	{
		locale: "sw-TZ",
		name: "Swahili, Tanzania",
		nativeName: "Kiswahili, Tanzania",
		direction: "ltr",
		country: "Tanzania",
		countryCode: "tz",
		hex: "#00A3DD",
		rgb: [0, 163, 221],
		color: 41949
	},
	{
		locale: "ss-ZA",
		name: "Swati",
		nativeName: "SiSwati",
		direction: "ltr",
		country: "Eswatini",
		countryCode: "sz",
		hex: "#3E5EB9",
		rgb: [62, 94, 185],
		color: 4087481
	},
	{
		locale: "sv-SE",
		name: "Swedish",
		nativeName: "Svenska",
		direction: "ltr",
		country: "Sweden",
		countryCode: "se",
		emoji: "🇸🇪",
		hex: "#FECC02",
		rgb: [254, 204, 2],
		color: 16698370
	},
	{
		locale: "sv-FI",
		name: "Swedish, Finland",
		nativeName: "Svenska, Finland",
		direction: "ltr",
		country: "Finland",
		countryCode: "fi",
		emoji: "🇫🇮",
		hex: "#002F6C",
		rgb: [0, 47, 108],
		color: 12140
	},
	{
		locale: "syc-SY",
		name: "Syriac",
		nativeName: "ܠܫܵܢܵܐ ܣܘܪܝܝܐ",
		direction: "rtl",
		country: "Syria",
		countryCode: "sy",
		hex: "#CE1126",
		rgb: [206, 17, 38],
		color: 13504806
	},
	{
		locale: "tl-PH",
		name: "Tagalog",
		nativeName: "Tagalog",
		direction: "ltr",
		country: "Philippines",
		countryCode: "ph",
		emoji: "🇵🇭",
		hex: "#0038A8",
		rgb: [0, 56, 168],
		color: 14504
	},
	{
		locale: "ty-PF",
		name: "Tahitian",
		nativeName: "Te reo tahiti",
		direction: "ltr",
		country: "French Polynesia",
		countryCode: "pf",
		emoji: "🇵🇫",
		hex: "#CE1126",
		rgb: [206, 17, 38],
		color: 13504806
	},
	{
		locale: "tg-TJ",
		name: "Tajik",
		nativeName: "Тоҷики",
		direction: "ltr",
		country: "Tajikistan",
		countryCode: "tj",
		emoji: "🇹🇯",
		hex: "#CC0000",
		rgb: [204, 0, 0],
		color: 13369344
	},
	{
		locale: "tzl-TZL",
		name: "Talossan",
		nativeName: "El bel glheþ Talossan",
		direction: "ltr",
		country: "Talossa",
		countryCode: "tzl",
		hex: "#707070",
		rgb: [112, 112, 112],
		color: 7368816
	},
	{
		locale: "ta-IN",
		name: "Tamil",
		nativeName: "தமிழ்",
		direction: "ltr",
		country: "India",
		countryCode: "in",
		emoji: "🇮🇳",
		hex: "#FF9933",
		rgb: [255, 153, 51],
		color: 16750899
	},
	{
		locale: "tt-RU",
		name: "Tatar",
		nativeName: "Татарча",
		direction: "ltr",
		country: "Russia",
		countryCode: "ru",
		region: "Tatarstan",
		regionCode: "ta",
		hex: "#008000",
		rgb: [0, 128, 0],
		color: 32768
	},
	{
		locale: "te-IN",
		name: "Telugu",
		nativeName: "తెలుగు",
		direction: "ltr",
		country: "India",
		countryCode: "in",
		emoji: "🇮🇳",
		hex: "#FF9933",
		rgb: [255, 153, 51],
		color: 16750899
	},
	{
		locale: "kdh-KDH",
		name: "Tem (Kotokoli)",
		nativeName: "Temba",
		direction: "ltr",
		country: "Togo",
		countryCode: "tg",
		emoji: "🇹🇬",
		hex: "#006A4A",
		rgb: [0, 106, 74],
		color: 27210
	},
	{
		locale: "th-TH",
		name: "Thai",
		nativeName: "ไทย",
		direction: "ltr",
		country: "Thailand",
		countryCode: "th",
		emoji: "🇹🇭",
		hex: "#00247D",
		rgb: [0, 36, 125],
		color: 9341
	},
	{
		locale: "bo-BT",
		name: "Tibetan",
		nativeName: "བོད་སྐད་",
		direction: "ltr",
		country: "Bhutan",
		countryCode: "bt",
		emoji: "🇧🇹",
		hex: "#29166F",
		rgb: [41, 22, 111],
		color: 2692719
	},
	{
		locale: "ti-ER",
		name: "Tigrinya",
		nativeName: "ትግርኛ",
		direction: "ltr",
		country: "Eritrea",
		countryCode: "er",
		emoji: "🇪🇷",
		hex: "#43B02A",
		rgb: [67, 176, 42],
		color: 4436010
	},
	{
		locale: "ts-ZA",
		name: "Tsonga",
		nativeName: "XiTsonga",
		direction: "ltr",
		country: "South Africa",
		countryCode: "za",
		emoji: "🇿🇦",
		hex: "#FFB81C",
		rgb: [255, 182, 18],
		color: 16758290
	},
	{
		locale: "tn-ZA",
		name: "Tswana",
		nativeName: "Setswana",
		direction: "ltr",
		country: "Botswana",
		countryCode: "bw",
		emoji: "🇧🇼",
		hex: "#ABCAE9",
		rgb: [171, 202, 233],
		color: 11258601
	},
	{
		locale: "tr-TR",
		name: "Turkish",
		nativeName: "Türkçe",
		direction: "ltr",
		country: "Turkey",
		countryCode: "tr",
		emoji: "🇹🇷",
		hex: "#E30A17",
		rgb: [227, 10, 23],
		color: 14879255
	},
	{
		locale: "tr-CY",
		name: "Turkish, Cyprus",
		nativeName: "Türkçe, Kıbrıs",
		direction: "ltr",
		country: "Cyprus",
		countryCode: "cy",
		emoji: "🇨🇾",
		hex: "#D57800",
		rgb: [213, 120, 0],
		color: 13989888
	},
	{
		locale: "tk-TM",
		name: "Turkmen",
		nativeName: "Түркmенче",
		direction: "ltr",
		country: "Turkmenistan",
		countryCode: "tm",
		emoji: "🇹🇲",
		hex: "#009639",
		rgb: [0, 150, 57],
		color: 38457
	},
	{
		locale: "uk-UA",
		name: "Ukrainian",
		nativeName: "Українська",
		direction: "ltr",
		country: "Ukraine",
		countryCode: "ua",
		emoji: "🇺🇦",
		hex: "#FFD700",
		rgb: [255, 215, 0],
		color: 16766720
	},
	{
		locale: "hsb-DE",
		name: "Upper Sorbian",
		nativeName: "Hornjoserbsce",
		direction: "ltr",
		country: "Germany",
		countryCode: "de",
		emoji: "🇩🇪",
		hex: "#0C4076",
		rgb: [12, 64, 118],
		color: 802934
	},
	{
		locale: "ur-IN",
		name: "Urdu, India",
		nativeName: "اردو، ہندوستان",
		direction: "rtl",
		country: "India",
		countryCode: "in",
		emoji: "🇮🇳",
		hex: "#FF9933",
		rgb: [255, 153, 51],
		color: 16750899
	},
	{
		locale: "ur-PK",
		name: "Urdu, Pakistan",
		nativeName: "اردو، پاکستان",
		direction: "rtl",
		country: "Pakistan",
		countryCode: "pk",
		emoji: "🇵🇰",
		hex: "#00401A",
		rgb: [0, 64, 26],
		color: 16410
	},
	{
		locale: "ug-CN",
		name: "Uyghur",
		nativeName: "Уйғур",
		direction: "rtl",
		country: "China",
		countryCode: "cn",
		emoji: "🇨🇳",
		region: "Xinjiang",
		regionCode: "ug",
		hex: "#0099FF",
		rgb: [0, 153, 255],
		color: 39423
	},
	{
		locale: "uz-UZ",
		name: "Uzbek",
		nativeName: "O’zbek",
		direction: "ltr",
		country: "Uzbekistan",
		countryCode: "uz",
		emoji: "🇺🇿",
		hex: "#009AB6",
		rgb: [0, 154, 182],
		color: 39606
	},
	{
		locale: "val-ES",
		name: "Valencian",
		nativeName: "Valencià",
		direction: "ltr",
		country: "Spain",
		countryCode: "es",
		emoji: "🇪🇸",
		region: "Valencia",
		regionCode: "val",
		hex: "#FF0000",
		rgb: [255, 0, 0],
		color: 16711680
	},
	{
		locale: "ve-ZA",
		name: "Venda",
		nativeName: "TshiVenḓa",
		direction: "ltr",
		country: "South Africa",
		countryCode: "za",
		emoji: "🇿🇦",
		hex: "#FFB81C",
		rgb: [255, 182, 18],
		color: 16758290
	},
	{
		locale: "vec-IT",
		name: "Venetian",
		nativeName: "Vèneto",
		direction: "ltr",
		country: "Italy",
		countryCode: "it",
		emoji: "🇮🇹",
		region: "Venice",
		regionCode: "vec",
		hex: "#980000",
		rgb: [152, 0, 0],
		color: 9961472
	},
	{
		locale: "vi-VN",
		name: "Vietnamese",
		nativeName: "Tiếng việt",
		direction: "ltr",
		country: "Vietnam",
		countryCode: "vn",
		emoji: "🇻🇳",
		hex: "#DA251D",
		rgb: [218, 37, 29],
		color: 14296349
	},
	{
		locale: "wa-BE",
		name: "Walloon",
		nativeName: "Walon",
		direction: "ltr",
		country: "Belgium",
		countryCode: "be",
		emoji: "🇧🇪",
		region: "Wallonia",
		regionCode: "wa",
		hex: "#FFFF00",
		rgb: [255, 255, 0],
		color: 16776960
	},
	{
		locale: "cy-GB",
		name: "Welsh",
		nativeName: "Cymraeg",
		direction: "ltr",
		country: "United Kingdom",
		countryCode: "gb",
		emoji: "🇬🇧",
		region: "Wales",
		regionCode: "cy",
		hex: "#D30731",
		rgb: [211, 7, 49],
		color: 13829937
	},
	{
		locale: "wo-SN",
		name: "Wolof",
		nativeName: "Wollof",
		direction: "ltr",
		country: "Senegal",
		countryCode: "sn",
		emoji: "🇸🇳",
		hex: "#009639",
		rgb: [0, 150, 57],
		color: 38457
	},
	{
		locale: "xh-ZA",
		name: "Xhosa",
		nativeName: "IsiXhosa",
		direction: "ltr",
		country: "South Africa",
		countryCode: "za",
		emoji: "🇿🇦",
		hex: "#FFB81C",
		rgb: [255, 182, 18],
		color: 16758290
	},
	{
		locale: "yi-DE",
		name: "Yiddish",
		nativeName: "ייִדיש",
		direction: "rtl",
		country: "Germany",
		countryCode: "de",
		emoji: "🇩🇪",
		hex: "#000000",
		rgb: [0, 0, 0],
		color: 0
	},
	{
		locale: "yo-NG",
		name: "Yoruba",
		nativeName: "Yorùbá",
		direction: "ltr",
		country: "Nigeria",
		countryCode: "ng",
		emoji: "🇳🇬",
		hex: "#008753",
		rgb: [0, 135, 83],
		color: 34643
	},
	{
		locale: "zea-ZEA",
		name: "Zeelandic",
		nativeName: "Zeêuws",
		direction: "ltr",
		country: "Netherlands",
		countryCode: "nl",
		emoji: "🇳🇱",
		region: "Zeeland",
		regionCode: "zea",
		hex: "#123484",
		rgb: [18, 52, 132],
		color: 1193092
	},
	{
		locale: "zu-ZA",
		name: "Zulu",
		nativeName: "IsiZulu",
		direction: "ltr",
		country: "South Africa",
		countryCode: "za",
		emoji: "🇿🇦",
		hex: "#FFB81C",
		rgb: [255, 182, 18],
		color: 16758290
	}
];

export default languages;
